### ISSUE TITLE
Login in not working in Natural Crit (even with right login and password)

### ISSUE THREAD

**Issue by zippdementia** [stolksdorf/naturalcrit#83]
So I put in my username and password, the page accepts it and goes to redirect and... nothing happens. If I then go to the Homebrewery page, I'm not logged in. What gives?

**Comment by M1k30n3** [comment]
Me too and there is no password recovery. Sad  i was working several things hope this gets fixed

**Comment by clockworkscholar** [comment]
Same here. I tried reloading the page several times, restarting my computer, and all the standard stuff. Nada.

**Comment by karkatsanger** [comment]
There's definitely something weird. I tried making a new account and logging in with that, but that didn't work either.

**Comment by cintain** [comment]
Hello, I am having the same problem. I tried logging in several times, and I can't access my account or content. Like a previous commenter said, there is no password recovery option. I would like to recover my homebrew content. Help!

**Comment by M1k30n3** [comment]
Hello:

Try to log in you will see a massage below the log in box saying that you
are. Then return to the Homebrew classic page and try to save that page,
refresh that page and you should be able to see your user in the top right
corner as normal. I am working with it the issues were resolved yesterday.
On Dec 20, 2018 19:12, "cintain" <notifications@github.com> wrote:

Hello, I am having the same problem. I tried logging in several times, and
I can't access my account or content. Like a previous commenter said, there
is no password recovery option. I would like to recover my homebrew
content. Help!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/stolksdorf/naturalcrit/issues/83#issuecomment-449167531>,
or mute the thread

**Comment by cintain** [comment]
Hello, 

I’ve tried this, but I still can’t login. It is possible I have forgotten my password. Is there a password reset utility?

I look forward to your reply. 

Cintain 昆遊龍
http://thewanderingdragon.net
Twitter: @cintain
“The Sage rules by emptying hearts and stuffing bellies, weakening ambitions and strengthening bones.” 道德經，3
